import { StrictMode, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import { emptyProject, koreanPrinciples, mathPrinciples, type ProblemProject, type Subject } from './types'
import { isProjectList, loadPrinciples, loadProjects, savePrinciples, saveProjects } from './storage'
import { generatePrompt } from './prompt'

const statusLabel = { idea: '아이디어', prompted: '프롬프트 완성', generated: '문제 생성됨', reviewing: '검토 중', complete: '완성' }

function App() {
  const [projects, setProjects] = useState<ProblemProject[]>(loadProjects)
  const [activeId, setActiveId] = useState(() => loadProjects()[0]?.id ?? '')
  const [principles, setPrinciples] = useState(loadPrinciples)
  const [query, setQuery] = useState(''); const [subjectFilter, setSubjectFilter] = useState('all')
  const [saveState, setSaveState] = useState('저장됨'); const [notice, setNotice] = useState('')
  const importRef = useRef<HTMLInputElement>(null)
  const active = projects.find((item) => item.id === activeId) ?? null
  const filtered = useMemo(() => projects.filter((item) => (subjectFilter === 'all' || item.subject === subjectFilter) && `${item.title} ${item.unit} ${item.topic}`.toLowerCase().includes(query.toLowerCase())), [projects, query, subjectFilter])
  useEffect(() => { if (!projects.length) { const project = emptyProject(); setProjects([project]); setActiveId(project.id) } }, [projects.length])
  useEffect(() => { setSaveState('저장 중...'); const timer = window.setTimeout(() => { saveProjects(projects); setSaveState('저장됨') }, 450); return () => clearTimeout(timer) }, [projects])
  const update = (patch: Partial<ProblemProject>) => { if (!active) return; setProjects((items) => items.map((item) => item.id === active.id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item)) }
  const create = (subject: Subject) => { const project = emptyProject(subject); setProjects((items) => [project, ...items]); setActiveId(project.id) }
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2200) }
  const copy = async () => { if (!active?.generatedPrompt) return; try { await navigator.clipboard.writeText(active.generatedPrompt); notify('프롬프트를 복사했습니다.') } catch { notify('복사에 실패했습니다. 프롬프트를 직접 선택해 복사하세요.') } }
  const exportData = () => { const blob = new Blob([JSON.stringify({ projects, principles }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `문제-제작-연구소-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href) }
  const importData = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const data: unknown = JSON.parse(String(reader.result)); const list = Array.isArray(data) ? data : (data as { projects?: unknown }).projects; if (!isProjectList(list)) throw new Error(); setProjects(list); setActiveId(list[0]?.id ?? ''); const saved = (data as { principles?: Record<string, string[]> }).principles; if (saved) { setPrinciples(saved); savePrinciples(saved) }; notify('백업 데이터를 불러왔습니다.') } catch { notify('올바른 백업 JSON 파일이 아닙니다.') } }; reader.readAsText(file) }
  if (!active) return null
  const currentPrinciples = principles[active.subject] ?? (active.subject === 'math' ? mathPrinciples : koreanPrinciples)
  return <main>
    <header><div><span className="eyebrow">LOCAL QUESTION DESIGN WORKBENCH</span><h1>문제 제작 연구소</h1></div><div className="header-actions"><span className="saved">● {saveState}</span><button onClick={exportData}>JSON 내보내기</button><button onClick={() => importRef.current?.click()}>가져오기</button><input ref={importRef} type="file" accept="application/json" hidden onChange={(event) => importData(event.target.files?.[0])} /></div></header>
    {notice && <div className="toast">{notice}</div>}
    <div className="layout simple-layout">
      <aside><div className="side-title"><h2>문제 프로젝트</h2><button className="primary" onClick={() => create('math')}>+ 새 문제</button></div><input placeholder="제목·단원 검색" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={subjectFilter} onChange={(event) => setSubjectFilter(event.target.value)}><option value="all">모든 과목</option><option value="math">수학</option><option value="korean">국어</option></select><div className="projects">{filtered.map((project) => <button className={`project ${project.id === active.id ? 'active' : ''}`} key={project.id} onClick={() => setActiveId(project.id)}><strong>{project.title}</strong><span>{project.subject === 'math' ? '수학' : '국어'} · {project.unit || '단원 미정'} · 난이도 {project.difficulty}</span><small>{statusLabel[project.status]} · {new Date(project.updatedAt).toLocaleDateString('ko-KR')}</small></button>)}</div><div className="new-subject"><button onClick={() => create('math')}>수학 만들기</button><button onClick={() => create('korean')}>국어 만들기</button></div><hr /><h3>나의 출제 원칙</h3><textarea aria-label="출제 원칙" value={currentPrinciples.join('\n')} onChange={(event) => { const next = { ...principles, [active.subject]: event.target.value.split('\n').filter(Boolean) }; setPrinciples(next); savePrinciples(next) }} /></aside>
      <section className="editor concise-editor"><div className="section-title"><div><span className="eyebrow">PROMPT BUILDER</span><h2>문제 만들기</h2></div><select value={active.subject} onChange={(event) => update({ subject: event.target.value as Subject })}><option value="math">수학</option><option value="korean">국어</option></select></div><p className="intro">필요한 정보만 입력하면 외부 AI에 바로 전달할 출제 프롬프트를 만듭니다.</p><div className="form-grid"><label>문제 제목<input value={active.title} onChange={(event) => update({ title: event.target.value })} /></label><label>문항 형식<select value={active.questionType} onChange={(event) => update({ questionType: event.target.value as 'multiple' | 'short' })}><option value="multiple">객관식</option><option value="short">주관식</option></select></label><label>단원명 / 영역<input placeholder={active.subject === 'math' ? '예: 함수의 극한' : '예: 독서, 문학'} value={active.unit} onChange={(event) => update({ unit: event.target.value })} /></label><label>핵심 개념<input placeholder="예: 합성함수, 화자의 태도" value={active.topic} onChange={(event) => update({ topic: event.target.value })} /></label></div>
      {active.subject === 'math' ? <MathForm project={active} update={update} /> : <KoreanForm project={active} update={update} />}
      <label>출제 의도<textarea value={active.idea} onChange={(event) => update({ idea: event.target.value })} placeholder="이 문제에서 학생이 어떤 사고를 하길 원하는지 자유롭게 적어보세요." /></label><label>기타 요구 사항<textarea value={active.reference} onChange={(event) => update({ reference: event.target.value })} placeholder="반드시 포함할 요소, 피하고 싶은 방식 등" /></label><div className="actions"><button className="primary" onClick={() => update({ generatedPrompt: generatePrompt(active, currentPrinciples), status: 'prompted' })}>프롬프트 생성</button><button onClick={() => update({ generatedPrompt: '' })}>초기화</button></div><label>생성된 프롬프트 <small>{active.generatedPrompt.length.toLocaleString()}자</small><textarea className="prompt" value={active.generatedPrompt} onChange={(event) => update({ generatedPrompt: event.target.value })} placeholder="프롬프트 생성 버튼을 누르면 여기에 표시됩니다." /></label><button className="primary wide" onClick={copy}>프롬프트 복사</button><p className="hint bottom-hint">자동 검토·검산 단계는 현재 화면에서 제외했습니다. 생성한 프롬프트를 외부 AI에 붙여넣어 사용하세요.</p></section>
    </div>
  </main>
}

function Difficulty({ value, update }: { value: number; update: (difficulty: number) => void }) { return <label className="difficulty">난이도 <b>{value}/5</b><input type="range" min="1" max="5" value={value} onChange={(event) => update(Number(event.target.value))} /><span>쉬움</span><span>어려움</span></label> }
function MathForm({ project, update }: { project: ProblemProject; update: (patch: Partial<ProblemProject>) => void }) { return <><label>계산 범위<input value={project.calculationScope ?? ''} onChange={(event) => update({ calculationScope: event.target.value })} placeholder="예: 복잡한 계산은 피하고, 유리수 범위에서 깔끔하게" /></label><Difficulty value={project.difficulty} update={(difficulty) => update({ difficulty })} /></> }
function KoreanForm({ project, update }: { project: ProblemProject; update: (patch: Partial<ProblemProject>) => void }) { const mode = project.koreanMode ?? 'provided'; return <><fieldset><legend>국어 출제 방식</legend><label><input type="radio" name="korean-mode" checked={mode === 'provided'} onChange={() => update({ koreanMode: 'provided' })} /> 등록한 지문 안에서 출제</label><label><input type="radio" name="korean-mode" checked={mode === 'generated'} onChange={() => update({ koreanMode: 'generated' })} /> AI가 새 지문을 만들고 출제</label></fieldset>{mode === 'provided' ? <label>등록 지문 또는 작품<textarea value={project.passage} onChange={(event) => update({ passage: event.target.value })} placeholder="출제할 지문 또는 작품 일부를 붙여넣으세요." /></label> : <div className="form-grid"><label>지문 주제 또는 소재<input value={project.passageTopic ?? ''} onChange={(event) => update({ passageTopic: event.target.value })} placeholder="예: 도시 열섬 현상" /></label><label>지문 길이<select value={project.passageLength ?? 'medium'} onChange={(event) => update({ passageLength: event.target.value as 'short' | 'medium' | 'long' })}><option value="short">짧음</option><option value="medium">보통</option><option value="long">김</option></select></label></div>}<Difficulty value={project.difficulty} update={(difficulty) => update({ difficulty })} /></> }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
