import type { ProblemProject, ReviewResult } from './types'
const paired = (text: string) => { const pairs: Record<string, string> = { '(': ')', '[': ']', '{': '}' }; const stack: string[] = []; for (const c of text) { if (pairs[c]) stack.push(pairs[c]); else if (Object.values(pairs).includes(c) && stack.pop() !== c) return false } return stack.length === 0 }
export function reviewProject(p: ProblemProject): ReviewResult[] {
  const results: ReviewResult[] = []
  results.push({ id: 'body', level: p.problem.trim() ? 'pass' : 'error', label: '문제 본문', detail: p.problem.trim() ? '문제 본문이 입력되었습니다.' : '문제 본문을 입력하세요.' })
  if (p.questionType === 'multiple') { const filled = p.choices.filter((c) => c.trim()); results.push({ id: 'choices', level: filled.length === 5 ? 'pass' : 'error', label: '선택지 개수', detail: filled.length === 5 ? '선택지 5개가 입력되었습니다.' : `객관식은 선택지 5개가 필요합니다. (현재 ${filled.length}개)` }); const normalized = filled.map((c) => c.trim().replace(/\s+/g, ' ')); results.push({ id: 'duplicate', level: new Set(normalized).size === normalized.length ? 'pass' : 'error', label: '선택지 중복', detail: new Set(normalized).size === normalized.length ? '중복 선택지가 없습니다.' : '동일한 선택지가 있습니다.' }); const answerNumber = Number(p.answer.replace(/[^0-9]/g, '')); results.push({ id: 'answer', level: answerNumber >= 1 && answerNumber <= 5 ? 'pass' : 'warning', label: '정답 범위', detail: answerNumber >= 1 && answerNumber <= 5 ? '정답 번호가 선택지 범위 안입니다.' : '정답을 1~5 중 하나로 확인하세요.' }); const lengths = filled.map((c) => c.length); if (lengths.length) results.push({ id: 'length', level: Math.max(...lengths) > Math.max(60, Math.min(...lengths) * 3) ? 'warning' : 'pass', label: '선지 길이', detail: Math.max(...lengths) > Math.max(60, Math.min(...lengths) * 3) ? '유난히 긴 선택지가 있어 정답 단서가 될 수 있습니다.' : '선지 길이가 크게 치우치지 않았습니다.' }) }
  results.push({ id: 'brackets', level: paired(`${p.problem}\n${p.solution}`) ? 'pass' : 'warning', label: '괄호 짝', detail: paired(`${p.problem}\n${p.solution}`) ? '기본 괄호 짝이 맞습니다.' : '괄호 짝을 확인하세요.' })
  results.push({ id: 'solution', level: p.solution.trim() ? 'pass' : 'warning', label: '해설', detail: p.solution.trim() ? '해설이 입력되었습니다.' : '해설이 없어 사람이 정답 근거를 검토하기 어렵습니다.' })
  return results
}
